version: '2'

services:
  coredatastore.web:
    build:
      context: ../..
      dockerfile: app/Docker/Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "80:80"
    volumes:
      - ..:/app
